worlds=['japan','america','australia','denmark','iceland']
#打印原列表
print(worlds)
print()
#临时按字母排序列表
print(sorted(worlds))
print(worlds)
print()
#临时按字母反向排序列表
print(sorted(worlds,reverse=True))
print(worlds)
print()
#永久改变列表反向排序
worlds.reverse()
print(worlds)
print()
#再次永久反向，等于恢复列表
worlds.reverse()
print(worlds)
print()
#按字母顺序排序改变列表
worlds.sort()
print(worlds)
print()
#按字母反向顺序排序改变列表
worlds.sort(reverse=True)
print(worlds)
